### PR TITLE
feat: Add a utility method `synchronizeState` which syncs scenes and groups.

### LINKED ISSUE #54: Add a catchall sync method
Currently we have two methods to pull service side controls and groups
```
client.syncronizeScenes()
client.syncronizeGroups()
```

It would be great to roll these into a utility function on the client that calls both of them in turn.

```
client.syncronizeState()
```

### PR DESCRIPTION
**Pull request by ProbablePrime**
resolves #54

### CODE REVIEW

**Comment by kateract** [comment]
The Promise.all returns a `[IGroup[], IScene[]]`, would it be better to return that instead of void or just too confusing? [My in progress commit](https://github.com/kateract/interactive-node/commit/f68bc7a1f74aa19ff7f80057a8ff0fc57062d528)

**Comment by ProbablePrime** [comment]
Actually yeah that would be better. When working on an issue please let me know we can assign it to you :)

I'll close this and assign the issue to you if thats ok :D?

**Comment by ProbablePrime** [comment]
@kateract

**Comment by ProbablePrime** [comment]
Ok got the tests working. but some other tests are promise rejections

**Pull request merged**
