### PR TITLE
docs(README): update dead links

### PR DESCRIPTION
**Pull request by andrewl33**
Update 404s. The first two links might still need to be modified.

### CODE REVIEW

**Comment by ProbablePrime** [comment]
Hey @andrewl33 This is a great contribution. Can I ask why you closed it? If you're still interested we'd happily accept it. 

Dont worry too much about the build checks, we can help you get those resolved.

Thank you!

**Comment by andrewl33** [comment]
@ProbablePrime I was mostly unsure if I did it correctly! I'll go ahead and reopen it.

**Comment by ProbablePrime** [comment]
Yep this is good, dont worry about the message check :), we'll fix that in the merge. Thank you for your contribution!

**Comment by ProbablePrime** [comment]
#108 though

**Pull request merged**
